### ISSUE TITLE
Nav scrolling in Firefox

### ISSUE THREAD

**Issue by anthonyfuentes** [portfolio-central/jekyll-instagram-portfolio-theme#3]
The nav scrolling was not working when I tested it recently in Firefox. I was able to get it working while also preserving the functionality in Chrome with a minor change. P.s. Thank you for sharing your awesome work!

Change
// ~/web-dist/js/app.js
// Changed line 18 & 37 from
dom.body.animate(...);   
// to:
$('body, html').animate(...);

**Comment by ssokurenko** [comment]
Thank you @anthonyfuentes !
If you already have it fixed in your fork, please create a pull request, I would be glad to merge it.
Happy new year!
